services:
  - type: worker
    name: vpd-security-bot
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: WIT_AI_TOKEN
        sync: false